export const bookCategories = [
  "Alle",
  "Kochbuch",
  "Kinderbuch & Familie",
  "Fitness",
  "Gesundheit",
  "Ernährung",
  "Heilkunde",
  "Esoterik & Achtsamkeit",
  "Business & Ratgeber",
  "Tiere",
  "Natur & Abenteuer",
];

const C = {
  koch: "Kochbuch",
  kind: "Kinderbuch & Familie",
  fit: "Fitness",
  gesund: "Gesundheit",
  essen: "Ernährung",
  heil: "Heilkunde",
  achtsam: "Esoterik & Achtsamkeit",
  business: "Business & Ratgeber",
  tiere: "Tiere",
  natur: "Natur & Abenteuer",
};

const rows = [
  ["001", C.business, "Dein Buch, deine Wirkung"],
  ["002", C.achtsam, "Die Wissenschaft deiner Wirkung"],
  ["003", C.fit, "Pilates Akademos"],
  ["004", C.business, "Kleine Influencer – Blush Edition"],
  ["005", C.essen, "Ernährung wirksam coachen"],
  ["006", C.gesund, "Rückengesundheit"],
  ["007", C.fit, "Dein Start, deine Bestform"],
  ["008", C.business, "Dein Wissen, deine Wirkung"],
  ["009", C.fit, "Mindset & Muscle"],
  ["010", C.business, "Kleine Influencer – Editorial Edition"],
  ["011", C.essen, "Nourish Wirkung"],
  ["012", C.fit, "Yoga Panorama"],
  ["013", C.natur, "Nature Explorer Journal"],
  ["014", C.gesund, "Chronische Schmerzen verstehen"],
  ["015", C.business, "Die Stimme deiner Expertise"],
  ["016", C.fit, "Dein Start, dein Weg, dein Ziel"],
  ["016-B", C.natur, "Nature Explorer Field Notes"],
  ["017", C.gesund, "Chronische Schmerzen ganzheitlich behandeln"],
  ["018", C.business, "Dein Start, deine Stimme, deine Marke"],
  ["019", C.business, "Signature Authority System – Noir"],
  ["020", C.fit, "Strength & Focus"],
  ["021", C.essen, "Wissen, das Menschen stärkt"],
  ["022", C.achtsam, "Zen Motion"],
  ["023", C.fit, "Pilates Sandstone"],
  ["024", C.business, "Kleine Influencer – Royal Edition"],
  ["025", C.essen, "Die Teller-Methode"],
  ["026", C.business, "Wissen wird Wirkung"],
  ["027", C.fit, "Black Ember Performance"],
  ["028", C.gesund, "Ganzheitlich gesund"],
  ["029", C.business, "Signature Authority System – Plum"],
  ["030", C.business, "Knowledge in Motion"],
  ["031", C.achtsam, "Kleine Auszeit"],
  ["032", C.achtsam, "The Mindful Teacher"],
  ["033", C.fit, "Pilates Earth"],
  ["034", C.business, "Kleine Influencer – Cobalt Edition"],
  ["035", C.essen, "Nourish & Thrive"],
  ["036", C.business, "Start Small, Build Big"],
  ["037", C.fit, "Member Handbook"],
  ["038", C.gesund, "Back Pain Guide"],
  ["039", C.business, "Signature Authority System – Aubergine"],
  ["040", C.essen, "Golden Harvest Nutrition"],
  ["041", C.fit, "Elite Start"],
  ["042", C.achtsam, "Focus Flow"],
  ["043", C.achtsam, "Zurück zu dir"],
  ["044", C.fit, "Built Different"],
  ["045", C.achtsam, "Calm Balance"],
  ["046", C.fit, "Urban Performance"],
  ["047", C.gesund, "Wissen verstehen, anwenden"],
  ["048", C.fit, "Feminine Power"],
  ["049", C.natur, "Raus. Erleben. Wachsen."],
  ["050", C.business, "Discipline Creates Freedom"],
  ["051", C.fit, "Bewegung macht glücklich"],
  ["052", C.achtsam, "Lunar Ritual"],
  ["053", C.fit, "Digital Chrome"],
  ["054", C.fit, "Athletic Heritage"],
  ["055", C.gesund, "Biotech Atlas"],
  ["056", C.essen, "Coastal Balance"],
  ["057", C.achtsam, "Mind Garden"],
  ["058", C.fit, "Bold Impact"],
  ["059", C.achtsam, "Soul Flow"],
  ["060", C.business, "Black Edition Authority"],
  ["061", C.natur, "Alpine Focus"],
  ["062", C.fit, "Ignite Strength"],
  ["063", C.business, "Klar. Wirken. Verändern."],
  ["064", C.achtsam, "Ankommen. Atmen. Aufblühen."],
  ["065", C.fit, "Bewegung. Präzision. Balance."],
  ["066", C.business, "Story. Marke. Impact."],
  ["067", C.essen, "Essen. Verstehen. Wohlfühlen."],
  ["068", C.business, "Dein Start, deine Reise, deine Zukunft"],
  ["069", C.fit, "Gemeinsam stark, erfolgreich"],
  ["070", C.heil, "Wissen. Heilen. Helfen."],
  ["071", C.business, "Signature Authority System – Gold"],
  ["072", C.fit, "Neon Ascent"],
  ["073", C.essen, "Terra Forma"],
  ["074", C.business, "Midnight Orbit"],
  ["075", C.fit, "Aqua Motion"],
  ["076", C.essen, "Citrus Pop"],
  ["077", C.business, "Burgundy Code"],
  ["078", C.natur, "Forest Atlas"],
  ["079", C.achtsam, "Plum Ritual"],
  ["080", C.business, "Steel Grid"],
  ["081", C.business, "Sunset Mono"],
  ["082", C.fit, "EMS Performance Workbook"],
  ["083", C.fit, "Hybrid Functional Fit"],
  ["084", C.gesund, "Recovery Workbook"],
  ["085", C.heil, "Sports Medicine Workbook"],
  ["086", C.gesund, "Longevity Expert Workbook"],
  ["087", C.gesund, "Thriving Through Change"],
  ["088", C.achtsam, "Retreat Workbook"],
  ["089", C.fit, "Fuel. Focus. Perform."],
  ["090", C.koch, "Food Creator"],
  ["091", C.gesund, "Workplace Wellbeing Workbook"],
  ["092", C.heil, "Mein Physio Workbook"],
  ["093", C.heil, "Sportphysio Workbook"],
  ["094", C.heil, "Osteopathie"],
  ["095", C.heil, "Heilpraktiker"],
  ["096", C.heil, "Sportmedizin"],
  ["097", C.heil, "Ernährungsmedizin"],
  ["098", C.gesund, "Ärzte mit passender Spezialisierung"],
  ["099", C.gesund, "Adipositas-Zentren"],
  ["100", C.gesund, "Reha Advisor"],
  ["101", C.gesund, "Wissen. Praxis. Lebenszeit."],
  ["102", C.koch, "Signature Cuisine"],
  ["103", C.koch, "Menu & Moment"],
  ["104", C.koch, "Nordic Table"],
  ["105", C.koch, "Terroir"],
  ["106", C.koch, "Culinary Lab"],
  ["107", C.koch, "Mare & Terra"],
  ["108", C.koch, "Dessert Couture"],
  ["109", C.koch, "Fire Table"],
  ["110", C.koch, "Grande Table"],
  ["111", C.koch, "Atelier du Goût"],
  ["112", C.koch, "Riviera"],
  ["113", C.koch, "Alpine Cookbook"],
  ["114", C.koch, "Dune & Bloom"],
  ["115", C.koch, "Citadelle"],
  ["116", C.koch, "Palace Cookbook"],
  ["117", C.koch, "Botanical Wellness Cookbook"],
  ["118", C.koch, "Coastal Sanctuary"],
  ["119", C.koch, "Hartwell Manor"],
  ["120", C.koch, "Islands of Flavor"],
  ["121", C.koch, "Beyond the Plate"],
  ["122", C.koch, "Opaline Noir"],
  ["123", C.koch, "Kyoto Lacquer"],
  ["124", C.koch, "Amalfi Sunstone"],
  ["125", C.koch, "Arctic Glass"],
  ["126", C.koch, "Velvet Aubergine"],
  ["127", C.koch, "Terracotta Modernist"],
  ["128", C.koch, "Cobalt Porcelain"],
  ["129", C.koch, "Saffron Atelier"],
  ["130", C.koch, "Jade Imperial"],
  ["131", C.koch, "Copper Smoke"],
  ["132", C.koch, "Citrus Ember"],
  ["133", C.koch, "Desert Flame"],
  ["134", C.koch, "Coastal Fire"],
  ["135", C.koch, "Garden Smoke"],
  ["136", C.koch, "Asado Rosa"],
  ["137", C.koch, "Nordic Firelight"],
  ["138", C.koch, "Poolside Grill Club"],
  ["139", C.koch, "Olive & Coal"],
  ["140", C.koch, "Sunset Barbecue"],
  ["141", C.koch, "Botanical BBQ"],
  ["142", C.koch, "Pâtisserie Lumière"],
  ["143", C.koch, "Gelato Riviera"],
  ["144", C.koch, "Nordic Sugar Studio"],
  ["145", C.koch, "Berry Blush"],
  ["146", C.koch, "Citrus & Cream"],
  ["147", C.koch, "Botanical Pâtisserie"],
  ["148", C.koch, "Sunday Bakehouse"],
  ["149", C.koch, "Tokyo Sweet Minimal"],
  ["150", C.koch, "Caramel Studio"],
  ["151", C.koch, "Tropical Dolce"],
  ["152", C.kind, "Meine ersten Küchenabenteuer"],
  ["153", C.kind, "Bunt kochen macht Spaß"],
  ["154", C.kind, "Kawaii Bento & Sweet Snacks"],
  ["155", C.kind, "Küchenlabor für junge Entdecker"],
  ["156", C.kind, "Backclub & Sweet Friends"],
  ["157", C.kind, "Street Food Lab"],
  ["158", C.kind, "Young Fuel"],
  ["159", C.kind, "Manga Sweets Studio"],
  ["160", C.kind, "Junge Kochakademie"],
  ["161", C.kind, "World Kitchen Kids"],
  ["162", C.kind, "Buchstaben-Abenteuer"],
  ["163", C.kind, "Zahlen-Safari"],
  ["164", C.kind, "Forscherlabor Kids"],
  ["165", C.kind, "Creative English Club"],
  ["166", C.kind, "Kawaii Study Journal"],
  ["167", C.kind, "History Detectives"],
  ["168", C.kind, "Young Creator Coding Book"],
  ["169", C.kind, "Teen Lern-Power"],
  ["170", C.kind, "World Cultures for Kids"],
  ["171", C.kind, "Gute Nacht, Waldfreunde"],
  ["172", C.kind, "Mondreise ins Traumland"],
  ["173", C.kind, "Schlaf schön, kleiner Panda"],
  ["174", C.kind, "Mein Zuckerstern"],
  ["175", C.kind, "Stoffwechsel-Detektive"],
  ["176", C.kind, "Energiehelden im Alltag"],
  ["177", C.kind, "Balance im Körper"],
  ["178", C.kind, "Besonderes Essen, starke Kids"],
  ["179", C.kind, "Schlaflabor Kids"],
  ["180", C.kind, "Sanfte Nächte, starke Tage"],
  ["181", C.kind, "Kleine Stoffwechselsterne"],
  ["182", C.kind, "Energiehelden"],
  ["183", C.gesund, "Sanfte Stärke"],
  ["184", C.gesund, "Mein Stoffwechselplan"],
  ["185", C.gesund, "Dein Gleichgewicht"],
  ["186", C.kind, "Reise durch die Energiewelt"],
  ["187", C.achtsam, "Sakura Zen Retreat"],
  ["188", C.achtsam, "Nordic Light Spa"],
  ["189", C.achtsam, "Desert Rose Retreat"],
  ["190", C.achtsam, "Alpine Herb Wellness"],
  ["191", C.achtsam, "Celadon Wellness"],
  ["192", C.achtsam, "Botanical Conservatory Spa"],
  ["193", C.achtsam, "Pearl Lagoon Wellness"],
  ["194", C.achtsam, "Ayurveda Sun Palace"],
  ["195", C.achtsam, "Pastel Marble Retreat"],
  ["196", C.achtsam, "Tropical Bloom Spa"],
  ["197", C.achtsam, "Rose Quartz Retreat"],
  ["198", C.kind, "Matcha Blossom Maternity Care"],
  ["199", C.kind, "Nordic Family Nest"],
  ["200", C.kind, "Mama Wellness"],
  ["201", C.kind, "Moonlight Lullaby"],
  ["202", C.kind, "Clinical Luxe Maternity Method"],
  ["203", C.kind, "Waterlily Family Bloom"],
  ["204", C.kind, "Botanical Nursery Stories"],
  ["205", C.kind, "Inclusive Parenting Guide"],
  ["206", C.kind, "Peach Meadow Pregnancy"],
  ["207", C.achtsam, "Zen Blossom Breath"],
  ["208", C.achtsam, "Desert Breath Ritual"],
  ["209", C.achtsam, "Ocean Exhale"],
  ["210", C.achtsam, "Nordic Stillness"],
  ["211", C.achtsam, "Mediterranean Calm"],
  ["212", C.achtsam, "Lavender Cloud"],
  ["213", C.gesund, "Mediterranean Breath Coach"],
  ["214", C.gesund, "Clinical Calm Breathwork"],
  ["215", C.achtsam, "Sunrise Flow"],
  ["216", C.achtsam, "Celestial Bloom"],
  ["217", C.business, "Aurora Impact"],
  ["218", C.business, "Kintsugi Voice"],
  ["219", C.business, "Bold Momentum"],
  ["220", C.business, "Champagne Stage"],
  ["221", C.business, "Neo Mentor"],
  ["222", C.business, "Spotlight Grid"],
  ["223", C.business, "Sage Resonance"],
  ["224", C.business, "Insight Atlas"],
  ["225", C.business, "Future Voice"],
  ["226", C.business, "Global Story Lab"],
  ["227", C.koch, "Vignoble Heritage"],
  ["228", C.koch, "Rosé Table"],
  ["229", C.koch, "Nordic Preserve"],
  ["230", C.koch, "Olive Grove Mercato"],
  ["231", C.koch, "Sakura Pantry"],
  ["232", C.koch, "Champagne Cellar"],
  ["233", C.koch, "Botanical Gourmet Lab"],
  ["234", C.koch, "Alpine Creamery"],
  ["235", C.koch, "Amber Ferment"],
  ["236", C.koch, "Citrus Verde Casa"],
  ["237", C.tiere, "Zen Sakura Canine"],
  ["238", C.tiere, "Dein Wissen, dein Welpe, dein starkes Team"],
  ["239", C.tiere, "Tiertrainer & Hundetrainer"],
  ["240", C.tiere, "Training. Vertrauen. Team."],
  ["241", C.tiere, "Pet Coach Workbook"],
  ["242", C.tiere, "Willkommen im Rudel"],
  ["243", C.tiere, "Tiertrainer & Hundetrainer – Coastal"],
  ["244", C.tiere, "Große Liebe, harmonisches Familienleben"],
  ["245", C.tiere, "Maßgeschneiderte Erziehung"],
  ["246", C.business, "Dein Wissen, dein Business – Citrus"],
  ["247", C.business, "Sakura Focus"],
  ["248", C.business, "Terra Nomad"],
  ["249", C.business, "Dein Business, dein Wissen, dein Buch"],
  ["250", C.business, "Dein Wissen, dein Business – Cobalt"],
  ["251", C.business, "Deine Business-Rezepte"],
  ["252", C.business, "Digital Silk"],
  ["253", C.business, "Washi Balance"],
  ["254", C.business, "Peach Momentum"],
  ["255", C.business, "Alpine Signal"],
];

const categoryText = {
  [C.koch]: "Eine mehrseitige Editorialvorlage für Rezepte, Genuss und kulinarische Geschichten.",
  [C.kind]: "Eine freundliche, klar gegliederte Vorlage für Kinder- und Familieninhalte.",
  [C.fit]: "Eine dynamische Vorlage für Training, Bewegung und sportliche Programme.",
  [C.gesund]: "Eine ruhige, verständliche Vorlage für Gesundheitswissen und praktische Begleitung.",
  [C.essen]: "Eine übersichtliche Vorlage für Ernährung, Beratung und alltagstaugliche Pläne.",
  [C.heil]: "Eine seriöse Vorlage für Heilkunde, Therapie und fachliche Wissensvermittlung.",
  [C.achtsam]: "Eine atmosphärische Vorlage für Achtsamkeit, Rituale und innere Balance.",
  [C.business]: "Eine prägnante Vorlage für Expertise, Positionierung und praxisnahe Ratgeber.",
  [C.tiere]: "Eine zugängliche Vorlage für Tierwissen, Training und ein harmonisches Zusammenleben.",
  [C.natur]: "Eine bildstarke Vorlage für Naturerlebnisse, Reisen und Abenteuer.",
};

export const bookDesigns = rows.map(([number, bookCategory, title]) => ({
  title,
  status: `Buchvorlage ${number}`,
  category: "Bücher",
  bookCategory,
  area: bookCategory,
  text: categoryText[bookCategory],
  details: `${title} zeigt eine vollständige, mehrseitige Designrichtung. Farben, Typografie, Texte und Seitenaufbau werden für das jeweilige Buchprojekt individuell weiterentwickelt.`,
  image: `/assets/book-designs/${number.toLowerCase()}.webp`,
  href: "/digital/buchproduktion-ghostwriting",
}));
