export const navigation = [
  {
    label: "Digital",
    href: "/digital",
    items: [
      ["Websites erstellen lassen", "/digital/websites-erstellen-lassen"],
      ["Buchproduktion & Ghostwriting", "/digital/buchproduktion-ghostwriting"],
      ["Content & Social-Media-Beiträge", "/digital/social-media-content"],
      ["KI-Telefonassistenten", "/digital/ki-telefonassistenten"],
      ["KI-Werbung für Meta & Google", "/digital/ki-werbung-meta-google"],
      ["Apps & Software", "/digital/apps-software"],
    ],
  },
  {
    label: "Expertise",
    href: "/expertise",
    items: [
      ["KI-Schulungen & Consulting", "/expertise/ki-schulungen-consulting"],
      ["Chelonaki Academy", "/expertise/academy"],
      ["Ernährungsberatung", "/expertise/ernaehrungsberatung"],
    ],
  },
  {
    label: "Originals",
    href: "/originals",
    items: [
      ["Eigene Bücher", "/originals/buecher"],
      ["Eigene Apps", "/originals/apps"],
      ["Weitere digitale Produkte", "/originals/digitale-produkte"],
    ],
  },
];

export const worlds = [
  {
    number: "01",
    eyebrow: "Für Unternehmen & eigene Projekte",
    title: "Chelonaki Digital",
    text: "Digitale Lösungen für Unternehmen, künftige Gründer und Menschen mit einer eigenen Idee.",
    detail: "Websites, Bücher, Content, Telefonassistenten, Ads und Apps",
    href: "/digital",
    cta: "Digital entdecken",
    tone: "digital",
  },
  {
    number: "02",
    eyebrow: "Wissen in Anwendung",
    title: "Chelonaki Expertise",
    text: "Künstliche Intelligenz trifft auf Beratung, Ernährungswissenschaft und echte Praxiserfahrung.",
    detail: "KI-Schulungen, Consulting, Academy und Ernährungsberatung",
    href: "/expertise",
    cta: "Expertise entdecken",
    tone: "expertise",
  },
  {
    number: "03",
    eyebrow: "Eigene Ideenwelten",
    title: "Chelonaki Originals",
    text: "Eigene Bücher, Apps und digitale Produkte mit Haltung, Gestaltung und langfristiger Vision.",
    detail: "Bücher, Apps und weitere digitale Produkte",
    href: "/originals",
    cta: "Originals entdecken",
    tone: "originals",
  },
];

export const hubData = {
  digital: {
    label: "Für Unternehmen & eigene Projekte",
    title: "Digitale Lösungen, die aus Ihrer Idee etwas Greifbares machen.",
    intro: "Für bestehende Unternehmen, künftige Gründungen und persönliche Vorhaben verbinden wir Strategie, Gestaltung, Technik und kontrollierte Automatisierung.",
    image: "/assets/project-digital-brand.png",
    cta: "Digitalprojekt anfragen",
    cards: navigation[0].items.map(([title, href], index) => ({
      title,
      href,
      text: [
        "Hochwertige Auftritte und Shops mit klarer Conversion-Struktur.",
        "Komplette Bücher: Konzept, Ghostwriting, Recherche, Design und veröffentlichungsfähige Dateien.",
        "Planbare Inhalte mit eigener Tonalität, Bildwelt und Qualitätskontrolle.",
        "Erreichbar bleiben, Anfragen strukturieren und Termine koordinieren.",
        "Kampagnen, Creatives, Tracking und Optimierung als zusammenhängendes System.",
        "Modulare Produkte, Portale und Workflows statt kurzfristiger Demos.",
      ][index],
    })),
  },
  expertise: {
    label: "Chelonaki Expertise",
    title: "Wissen wird erst wertvoll, wenn es anwendbar wird.",
    intro: "Wir übersetzen künstliche Intelligenz, Ernährungswissenschaft und Praxiserfahrung in klare Entscheidungen, wirksame Beratung und strukturierte Lernangebote.",
    image: "/assets/chapter-architecture.webp",
    cta: "Erstgespräch buchen",
    cards: navigation[1].items.map(([title, href], index) => ({
      title,
      href,
      text: [
        "Prozesse verstehen, sinnvolle Anwendungsfälle priorisieren und umsetzen.",
        "Strukturierte Video-Lernwelten für KI und Ernährung.",
        "Wissenschaftlich fundierte Beratung für Unternehmen und Privatpersonen.",
      ][index],
    })),
  },
  originals: {
    label: "Chelonaki Original",
    title: "Eigene Ideen. Eigene Produkte. Eine gemeinsame Welt.",
    intro: "Unter Originals entstehen eigene Bücher, Apps und digitale Produkte, die Ernährung, Gesundheit und alltagstaugliches Wissen sinnvoll verbinden.",
    image: "/assets/project-nutrition-venture.png",
    cta: "Originals entdecken",
    cards: navigation[2].items.map(([title, href], index) => ({
      title,
      href,
      text: [
        "Fach- und Kinderbücher für Ernährung, Gesundheit und besondere Stoffwechselthemen.",
        "Eigene Ernährungs-, Fitness- und Alltagsanwendungen wie Chelonaki EvoFit.",
        "Kurse, Assistenten und personalisierte Inhalte im Chelonaki-Ökosystem.",
      ][index],
    })),
  },
};

const b2bNote = "Die dargestellten Paketpreise verstehen sich netto zuzüglich der gesetzlichen Umsatzsteuer und richten sich an Unternehmer im Sinne des § 14 BGB. Private Projekte sind ausdrücklich willkommen und erhalten vor Beauftragung ein gesondertes Angebot mit korrekt ausgewiesenem Gesamtpreis.";

export const services = {
  "/digital/websites-erstellen-lassen": {
    area: "Digital", label: "Für Unternehmen & eigene Projekte", title: "Websites, die nicht nur gut aussehen, sondern verkaufen.",
    intro: "Wir entwickeln Shopify-Websites und Shops von der Struktur über Design und Text bis zur responsiven Umsetzung und laufenden Optimierung.",
    problem: "Viele Websites erklären zu viel, führen zu wenig und werden nach dem Launch technisch nicht weitergedacht.",
    solution: ["Unternehmenswebsites und Shopify-Shops", "Landingpages und Conversion-Struktur", "Responsive Umsetzung und Basis-SEO", "Formulare, Newsletter, Termine und Integrationen"],
    steps: ["Ziel und Designrichtung festlegen", "Struktur und Inhalte entwickeln", "Shopify responsiv umsetzen", "Prüfen, freigeben und übergeben"],
    pricing: [
      { name: "Website Starter", price: "1.000 €", meta: "bis 5 Seiten · 2 Korrekturrunden" },
      { name: "Website Business", price: "1.750 €", meta: "bis 10 Seiten · Branding · Tracking-Grundsetup" },
      { name: "Website Pro", price: "2.500 €", meta: "bis 15 Seiten · Conversion · Blog · Newsletter", featured: true },
      { name: "Website Individual", price: "ab 2.900 €", meta: "individuelle UX/UI und Funktionen" },
    ],
    note: `${b2bNote} Shopify-Tarife, kostenpflichtige Apps und weitere Fremdkosten sind nicht enthalten.`,
    cta: "Website-Projekt besprechen",
    bookingCta: "Paket auswählen & Website buchen",
    inquiryCta: "Individuelle Website anfragen",
    insight: {
      label: "Warum Shopify",
      title: "Einfacher pflegen. Planbarer weiterentwickeln.",
      text: "Inhalte, Produkte, Bestellungen und viele alltägliche Einstellungen werden in einer zentralen Oberfläche verwaltet. Hosting, zentrale Plattformupdates und TLS-Zertifikate für verbundene Domains reduzieren den technischen Eigenbetrieb – ohne eine absolute Störungsfreiheit zu versprechen.",
      points: ["Zentrale Pflege statt verteilter Systeme", "Weniger selbst betriebene Basiskomponenten", "Direkt für Leistungen und Produkte erweiterbar", "Saubere Übergabe nach persönlicher Einweisung"],
    },
  },
  "/digital/social-media-content": {
    area: "Digital", label: "Für Unternehmen & eigene Projekte", title: "Ein Content-System statt täglicher Improvisation.",
    intro: "Wir planen, produzieren, prüfen und veröffentlichen Inhalte in einer eigenen Markenwelt – vollständig KI-gestützt, aber nicht ungeprüft.",
    problem: "Unregelmäßige Inhalte, wechselnde Bildsprachen und fehlende Prozesse kosten Reichweite und vor allem Zeit.",
    solution: ["KI-Videos und Karussells", "Marken-, Themen- und Stilkonzept", "Captions, Redaktionsplanung und Veröffentlichung", "Reporting und laufende Optimierung"],
    steps: ["Marke und Themen schärfen", "Produktionssystem definieren", "Freigabezyklus einrichten", "Veröffentlichen und optimieren"],
    pricing: [
      { name: "Content Basic", price: "500 €/Monat", meta: "20 KI-Videos · 40 Karussells à 5 Slides" },
      { name: "Content Business", price: "750 €/Monat", meta: "30 KI-Videos · 60 Karussells à 5 Slides", featured: true },
      { name: "Content Pro", price: "1.250 €/Monat", meta: "60 KI-Videos · 120 Karussells à 5 Slides" },
    ],
    note: `${b2bNote} Drehs, Darsteller, Studios, Sonderlizenzen und externe Produktionskosten sind nicht enthalten.`,
    cta: "Content-System anfragen",
    bookingCta: "Content-Paket auswählen & buchen",
    inquiryCta: "Individuelles Content-System anfragen",
  },
  "/digital/ki-telefonassistenten": {
    area: "Digital", label: "Für Unternehmen & eigene Projekte", title: "Erreichbar bleiben, ohne jeden Anruf selbst anzunehmen.",
    intro: "Der KI-Telefonassistent beantwortet wiederkehrende Fragen, nimmt Anliegen auf und koordiniert je nach Paket Termine, Leads oder Bestellungen.",
    problem: "Verpasste Anrufe bedeuten verpasste Kunden – gleichzeitig dürfen Datenschutz, Transparenz und Eskalation nicht dem Zufall überlassen werden.",
    solution: ["Eingehende Anrufe im vereinbarten Fair-Use-Rahmen", "FAQ, Nachrichten und Gesprächszusammenfassungen", "Termin- und Leadlogik", "CRM-, Shopify- oder API-Anbindung im Pro-Paket"],
    steps: ["Zweck und erlaubte Gesprächslogik klären", "Wissen und Eskalationen definieren", "Testgespräche und Freigabe", "Sicher starten und nachschärfen"],
    pricing: [
      { name: "Basic", price: "ab 69 €/Monat", meta: "828 € pro Jahr bei jährlicher Vorauszahlung" },
      { name: "Business", price: "ab 129 €/Monat", meta: "Termine · Leads · individuelle Logik", featured: true },
      { name: "Pro", price: "ab 219 €/Monat", meta: "Integrationen · mehrere Rufnummern · Workflows" },
    ],
    note: `${b2bNote} Monatlich kündbar ab 99 €/Monat zuzüglich 149 € Einrichtung. Ab drei Monaten Mindestlaufzeit entfällt die Einrichtungspauschale. Ausgehende Anrufe werden ab 0,12–0,19 €/Minute berechnet und erfolgen nur im rechtlich zulässigen Rahmen.`,
    cta: "Telefonassistent konfigurieren",
    bookingCta: "KI-Telefonassistent auswählen & buchen",
    inquiryCta: "Individuelle Integration anfragen",
  },
  "/digital/ki-werbung-meta-google": {
    area: "Digital", label: "Für Unternehmen & eigene Projekte", title: "Werbung, die Angebot, Creative und Zielseite zusammen denkt.",
    intro: "Chelonaki entwickelt und optimiert Meta- und Google-Kampagnen mit nachvollziehbarem Tracking und verständlichen Handlungsempfehlungen.",
    problem: "Einzelne Anzeigen ohne klare Botschaft, passende Landingpage und saubere Messung verbrennen Budget.",
    solution: ["Strategie und Zielgruppenanalyse", "Anzeigentexte, Bild- und Video-Creatives", "A/B-Tests, Remarketing und Tracking", "Budgetüberwachung, Reporting und Optimierung"],
    steps: ["Angebot und Ziel definieren", "Kampagne und Creatives bauen", "Tracking prüfen", "Testen und laufend optimieren"],
    pricing: [
      { name: "Ads Basic", price: "500 €/Monat", meta: "1 Plattform · bis 3 Kampagnen" },
      { name: "Ads Business", price: "750 €/Monat", meta: "2 Plattformen · bis 6 Kampagnen", featured: true },
      { name: "Ads Pro", price: "1.250 €/Monat", meta: "bis 3 Plattformen · Funnel und Strategie-Call" },
    ],
    note: `${b2bNote} Das Werbebudget und externe Tools sind nicht enthalten und werden direkt vom Kunden getragen.`,
    cta: "Werbekampagne besprechen",
    bookingCta: "Werbepaket auswählen & buchen",
    inquiryCta: "Individuelle Kampagne anfragen",
  },
  "/digital/apps-software": {
    area: "Digital", label: "Für Unternehmen, Gründer & Organisationen", title: "Aus einer Idee wird eine App, die Menschen wirklich nutzen können.",
    intro: "Wir entwickeln skalierbare Apps und digitale Produkte für iOS, Android und Web – individuell gestaltet, KI-gestützt und auf einer gemeinsamen technischen Basis.",
    problem: "Ein schneller KI-Prototyp ist noch kein belastbares Unternehmenssystem.",
    solution: ["iOS und Android aus gemeinsamer Codebasis", "Login, Datenbanken, Rollen und Adminbereiche", "Zahlungen, Push, APIs und KI-Funktionen", "Dokumentierte Architektur, Tests und Übergabe"],
    steps: ["Idee und Kernfunktionen prüfen", "Discovery, Nutzerwege und Daten festlegen", "UX/UI und Prototyp abstimmen", "Modular entwickeln, testen und übergeben"],
    pricing: [
      { name: "App Starter", price: "ab 2.500 €", meta: "5–8 Screens · iOS & Android · einfache API" },
      { name: "App MVP", price: "ab 4.900 €", meta: "Login · Datenbank · Admin · Push", featured: true },
      { name: "App Advanced", price: "ab 7.900 €", meta: "Rollen · Zahlungen · mehrere Schnittstellen" },
      { name: "App Pro", price: "ab 12.900 €", meta: "KI · Automationen · umfangreiches Backend" },
      { name: "Custom / Enterprise", price: "ab 20.000 €", meta: "individuelle Infrastruktur und Sicherheitsrahmen" },
    ],
    note: `${b2bNote} iOS und Android sind bei mobilen Standardpaketen aus gemeinsamer Codebasis vorgesehen. Web-App, Entwicklerkonten, Hosting, Datenbanken, Zahlungsanbieter sowie KI- und API-Dienste werden je nach Umfang separat ausgewiesen.`,
    cta: "Kostenlose Ersteinschätzung anfragen",
    bookingCta: "App-Paket auswählen & Projekt starten",
    inquiryCta: "Individuelle Software anfragen",
    insight: {
      label: "Multi-Platform App Development",
      title: "Ein Projekt. iOS und Android inklusive.",
      text: "Flutter oder React Native ermöglichen eine gemeinsame technische Basis. Das reduziert Doppelarbeit bei Entwicklung, Tests und Wartung. Eine Web-App wird abhängig vom Paket ergänzt.",
      points: ["Modular statt festgefahren", "Menschliche Prüfung kritischer Funktionen", "Security by Design nach Schutzbedarf", "Dokumentierte Übergabe und Ausbauplanung"],
    },
  },
  "/expertise/ki-schulungen-consulting": {
    area: "Expertise", label: "Für Unternehmen", title: "KI-Schulungen & Consulting für konkrete Arbeitsabläufe.",
    intro: "Wir analysieren, wo künstliche Intelligenz Zeit spart, Qualität verbessert oder neue Angebote ermöglicht – und übersetzen das in einen konkreten Umsetzungsweg.",
    problem: "Tool-Sammlungen ohne Prioritäten führen selten zu besseren Prozessen.",
    solution: ["KI-Strategie und Prozessanalyse", "Automatisierung wiederkehrender Aufgaben", "Werkzeugauswahl und eigene Assistenten", "Schulungen, Datenschutz und verantwortungsvoller Einsatz"],
    steps: ["Ist-Zustand verstehen", "Anwendungsfälle priorisieren", "Roadmap und Prototyp entwickeln", "Team befähigen und Einführung begleiten"],
    pricing: [
      { name: "Strategieberatung", price: "ab 149 €/Std.", meta: "fokussierte Einzelberatung" },
      { name: "KI-Schulung", price: "1.290 €", meta: "1 Tag · verständlich und praxisnah" },
      { name: "KI-Consulting", price: "1.490 €", meta: "1 Tag · Prozesse und Umsetzung" },
      { name: "KI-Intensivworkshop", price: "2.290 €", meta: "2 Tage · Analyse · Übungen · Fahrplan", featured: true },
      { name: "AI Transformation Sprint", price: "ab 3.990 €", meta: "Strategie, Prioritäten und Umsetzungsplan" },
    ],
    note: b2bNote,
    cta: "KI-Erstgespräch buchen",
    bookingCta: "KI-Schulung oder Beratung auswählen",
    inquiryCta: "KI-Erstgespräch buchen",
  },
  "/digital/buchproduktion-ghostwriting": {
    area: "Digital", label: "Für Unternehmen & eigene Buchprojekte", title: "Ihr Buch – geschrieben, gestaltet, veröffentlichungsfertig.",
    intro: "Wir übernehmen die komplette Buchproduktion: Konzept, Recherche, Ghostwriting, Cover, Layout sowie die fertigen Dateien für Print und E-Book.",
    problem: "Fachwissen ist vorhanden, aber Struktur, Zeit, Recherche und hochwertige Umsetzung fehlen.",
    solution: ["Buchkonzept, Positionierung und Kapitelstruktur", "Ghostwriting, Recherche und Quellen", "Cover, Buchsatz, Layout und Bildentwicklung", "Veröffentlichungsfertige PDF- und E-Book-Dateien"],
    steps: ["Idee und Material prüfen", "Konzept und Inhaltsverzeichnis freigeben", "Kapitelweise produzieren", "Lektorat, Layout und finale Freigabe"],
    pricing: [
      { name: "Kinderbuch", price: "ab 500 €", meta: "klar begrenzter Einstieg bis 24 Seiten" },
      { name: "Book Starter", price: "ab 1.000 €", meta: "bis ca. 80 Seiten · Basisdesign · Cover" },
      { name: "Authority Book", price: "3.000 €", meta: "ca. 80–150 Seiten · Konzept · Ghostwriting · Layout", featured: true },
      { name: "Premium Research Book", price: "6.000 €", meta: "Recherche · Quellen · Lektorat · hochwertiges Design" },
      { name: "Individuelles Buchprojekt", price: "auf Anfrage", meta: "Fachbücher, Sonderformate und größere Umfänge" },
    ],
    note: `${b2bNote} Druck, ISBN, Plattformgebühren, Sonderlizenzen und nicht ausdrücklich genannte Fremdleistungen sind nicht enthalten.`,
    cta: "Buchprojekt anfragen",
    bookingCta: "Buchpaket auswählen & Projekt starten",
    inquiryCta: "Individuelles Buchprojekt anfragen",
  },
};

export { b2bNote };
